name: williankirsch
description: Site pessoal e portifÃ³lio de Willian Kirsch.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.1+4

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  purple_ds:
    path: ../design_system/purple_design_system

  turttle:
    path: ../turttle

  scrollable_positioned_list: ^0.3.5
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    - assets/app-ads.txt
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/terceiros/

  fonts:
    - family: AnekLatin
      fonts:
        - asset: packages/purple_ds/fonts/AnekLatin-Regular.ttf
          weight: 400
        - asset: packages/purple_ds/fonts/AnekLatin-Medium.ttf
          weight: 500
        - asset: packages/purple_ds/fonts/AnekLatin-Bold.ttf
          weight: 700